---
# This role contains the steps to set up the haproxy configuration and container

- name:
  file:
    path: /etc/haproxy
    state: directory
    mode: 0755

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Add selfsigned cert
  copy: src=selfsigned.pem dest=/etc/haproxy/selfsigned.pem

- name: Add Dockerfile
  copy: src=Dockerfile dest=/etc/haproxy/Dockerfile

- name: Build the container
  docker_image:
     path: /etc/haproxy
     name: my-haproxy

- name: Start the container
  docker_container:
    name: haproxy-for-databases
    image: my-haproxy
    state: started
    ports:
     - "7500:7500/tcp"
     - "3607:3607/tcp"
    networks:
     - name: db-net
     - ipv4_address: "{{ haproxy_ip }}"
    devices:
     - "/etc/haproxy:/usr/local/etc/haproxy:ro"