---
# This role contains the steps to set up the haproxy configuration and container

- name:
  file:
    path: /etc/haproxy
    state: directory
    mode: 0755

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg