---
# This role contains the steps to set up the haproxy configuration and container

- name: Make the etc haproxy folder
  file:
    path: /etc/haproxy
    state: directory
    mode: 0755

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Add selfsigned cert
  copy: src=selfsigned.pem dest=/etc/haproxy/selfsigned.pem

- name: Add Dockerfile
  copy: src=Dockerfile dest=/etc/haproxy/Dockerfile

- name: Add unit file
  copy: src=haproxy_container.service dest=/etc/systemd/system/

- name: Add start script
  copy: src=start_haproxy.sh dest=/etc/haproxy/start_haproxy.sh

- name: Enable haproxy_container unit file
  systemd:
    name: haproxy_container.service
    daemon-reload: yes
    enabled: yes

- name: Build the container
  docker_image:
     path: /etc/haproxy
     name: my-haproxy

- name: Start the container
  docker_container:
    name: haproxy-for-databases
    image: my-haproxy
    state: started
    ports:
     - "7500:7500/tcp"
     - "3607:3607/tcp"
    networks:
     - name: db-net
       ipv4_address: "{{ haproxy_ip }}"
    volumes:
     - "/etc/haproxy:/usr/local/etc/haproxy:ro"