---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  
  roles:
  - common

- hosts: swarmmanager

  tasks:
  - name: Create the swarm
    docker_swarm:
      state: present

- hosts: swarmworker

  tasks:
  - name: Join as a worker
    docker_swarm:
      state: join

- hosts: swarmmanager

  tasks:
  - name: "create overlay network"
    docker_netowork:
      name: db-net
      driver: overlay
      ipam_options:
        subnet: '172.20.0.0/16'
        gateway: 172.20.0.2
        attachable: true

- hosts: all

  roles:
  - haproxy

# Example that prints the loopback address and gateway for each host
#- hosts: all
#  tasks:
#  - debug:
#    msg: "{{ docker_info }}"
