---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  
  roles:
  - common

- hosts: swarmmanager

  tasks:
  - name: "Create the swarm"
    docker_swarm:
      state: present
      advertise_addr: "{{ hostvars['mysql1']['ansible_default_ipv4']['address'] }}"
    register: swarm_info

- hosts: swarmworker

  tasks:
  - debug:
     msg: "{{ swarm_info }}"

  - name: Join as a worker
    docker_swarm:
      state: join
      advertise_addr: "{{ hostvars['mysql2']['ansible_default_ipv4']['address'] }}"
      join_token: swarm_facts.contains.JoinTokens.contains.Worker
      remote_addrs: "{{ hostvars['mysql1']['ansible_default_ipv4']['address'] }}"

- hosts: swarmmanager

  tasks:
  - name: "create overlay network"
    docker_network:
      name: db-net
      driver: overlay
      ipam_options:
        subnet: '172.20.0.0/16'
        gateway: 172.20.0.2
        attachable: true

- hosts: all

  roles:
  - haproxy

# Example that prints the loopback address and gateway for each host
#- hosts: all
#  tasks:
#  - debug:
#    msg: "{{ docker_info }}"
